### PR TITLE
Add support for easy mode

### PR DESCRIPTION
**Pull request by bboudaoud-nv**
This branch adds support for an "easy" mode w/ larger, slower moving targets for less skilled users. The effects of late warp may not be as pronounced, but this should provide an option for people less experienced in FPS gameplay.

You can set easy mode using the existing `mode` URL param as follows (though this link will not actually work until this PR is merged): 
[https://nvlabs.github.io/FPSWarpDemo?mode=easy](https://nvlabs.github.io/FPSWarpDemo?mode=easy)

In the meantime you can test it using `[repo location]/index.html?mode=easy`

### CODE REVIEW

**Comment by bboudaoud-nv** [comment]
After merging the [most recent changes from WebFPSci](https://github.com/NVlabs/WebFPSci/pull/1) this branch now supports additional parametrization of all experiment parameters from the URL. This should reduce the need for things like additional experiment modes in the future. 

We will still support `mode=easy`  to give a compact way to reduce experiment difficulty for now, though the same change could now be supported with `targetMinSize=1&targetMaxSize=2&targetMinSpeed=8&targetMaxSpeed=10`.

**Comment by jspjutNV** [comment]
I just gave this a shot, but increase `targetMinSize` to 2 and `targetMaxSize` to 3 and got the following results: 
image

I feel like the size 1 targets may still be a little too small for easy, but the size 3 targets are probably larger than we'd need given that quite a few targets seem to spawn close to the user.  I also find it weird that the "normal" max size is 3, but easy mode sets the max size smaller than that.

It's probably worth doing some tests or reviews to see what we think might be the best setting for "normal" and "easy". As a quick proposal, maybe 2-2.5 is a good "easy" range and 0.5-2 would be a good "normal" range. 

Another thing I noticed (but should probably be a separate PR/issue) is that sometimes the target respawning and motion ends up moving the aim very high. This makes aiming harder and a bit more annoying.

**Review by jspjutNV — APPROVED** [review]
Other than my minor comment on sizes, this looks good to me.

**Comment by bboudaoud-nv** [comment]
@jspjutNV I'll plan to make a commit to increase the target size to the range suggest (2-2.5 easy and 0.5-2 normal). I assume you are okay with the speed ranges being used.

I think the target spawn mechanics could be improved a bit in general in WebFPSci. Currently we spawn the target relative to the current view direction over a (uniformly randomized) azimuth/elevation range; however, it may make more sense to improve this mechanic to:
- Use an annual region to avoid spawning targets at near 0 azimuth _and_ elevation relative to the current view direction
- Bias targets towards the horizon when the view elevation starts to grow high/low

I'll go ahead and create an issue/branch in WebFPSci to help deal with this.

**Comment by bboudaoud-nv** [comment]
Quick side note, after playing with this a bit I'll probably use 0.5-1.5 for the "normal" mode targets, even a size 2 target seems a bit "too easy" now that we support an explicit easy mode and narrower range of target size should provide more consistent results between conditions.

**Review by jspjutNV — APPROVED** [review]

**Pull request merged**
